secrets:
    truenasHost: ENC[AES256_GCM,data:OO5bG36oBZ6st+YPbg==,iv:VlpjoQbfhsk8Ac6r+Up3XWPb/ysMILkralX1vEC1ZzQ=,tag:XCtaPKxhApNJEaeS/BJXNQ==,type:str]
    truenasApiKey: ENC[AES256_GCM,data:TYl9B8ylxvqsdhL1DiFFA232rkqd4AM8IX3xTRMrQMsrRaHMwyGaC66jTf7G5C5RbtwcLznV0iq67k7NEFiARCJI,iv:/k2zjLdKOjVnn4YiGqN1nPrAsAMbSQ/kJqoVU/wWBIo=,tag:ftFVZDRYxPiGwXzMifJOfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pq0dazk46s5mg8wdduccsx69sgu5namyls7q7pph0vx8nzrfsds0pnfvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eGxmaytYdThteHRPRjFy
            TDV0NDRiU1BtV0lwdDFDMnozRXRFRWl2UlZFCldCeWJRV1JGTUJSRy9TUDV1VkFZ
            TE9mM3hjQjNOSHZPbzAzSStRNi9tMUUKLS0tICtLZ0U3ZGxLOERKRVIvTVp5MnV3
            UUhKazRTOERXY0ZBRkNmVlIxUmpFQTAKunZbKcwFfak4Xfc4eeBwsvC5l6E7Ogfk
            gNYCyrmDOB3bVrbNXuSkFNXzNckTDxL0QlnnD6w0Hr+mhyLya3GDaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T23:39:05Z"
    mac: ENC[AES256_GCM,data:uj4EUxs84Xg59HyOZyCSXk1gOYH8ro0qe6mmesdux30LEuIiKcwv2MbDvnZsjnY/5jjPEAJCTieJQKZoChWKaFrPAaA3PPN+aoBq++w10khGE2JQizivmv2yHKk4l9MTDHrlsj3fPv9cpeqZY/oUvW/xnXkEyiaaLhxICd6+tIU=,iv:gZ7YZLB8I+tddx5UNkZnVDyQr5mwjGpFZCjA3i1yTV8=,tag:2H3P/seyh0e+pxlnCFEZRA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
