secrets:
    truenasHost: ENC[AES256_GCM,data:OO5bG36oBZ6st+YPbg==,iv:VlpjoQbfhsk8Ac6r+Up3XWPb/ysMILkralX1vEC1ZzQ=,tag:XCtaPKxhApNJEaeS/BJXNQ==,type:str]
    truenasApiKey: ENC[AES256_GCM,data:TYl9B8ylxvqsdhL1DiFFA232rkqd4AM8IX3xTRMrQMsrRaHMwyGaC66jTf7G5C5RbtwcLznV0iq67k7NEFiARCJI,iv:/k2zjLdKOjVnn4YiGqN1nPrAsAMbSQ/kJqoVU/wWBIo=,tag:ftFVZDRYxPiGwXzMifJOfA==,type:str]
    seerrApiKey: ENC[AES256_GCM,data:vDeLu996zOnFickeiP08ORkHFSTh/ZQTjM0gp+EtqpejZ2kIIA2hFU42U9lq7AE2s1VcVMWNSOF+4p+shhK/vxrDZeE=,iv:spDrBAKuy1pR86CqBycqIbIZ+5sgnFcXNzUb/SQ7Zq4=,tag:t6KU/CI1WYpKqJOFUVVDNA==,type:str]
    jellyfinApiKey: ENC[AES256_GCM,data:T3JwzesivfEfnmDpzNcMM9nnl/SdSuVp4ptduGhcc54=,iv:mRqxdUD2WlPEgLLxC1uEk/YuP1ufNfg3iLTFNGbjY2o=,tag:xVlvHhsC0zEmoj9/tuQfBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pq0dazk46s5mg8wdduccsx69sgu5namyls7q7pph0vx8nzrfsds0pnfvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eGxmaytYdThteHRPRjFy
            TDV0NDRiU1BtV0lwdDFDMnozRXRFRWl2UlZFCldCeWJRV1JGTUJSRy9TUDV1VkFZ
            TE9mM3hjQjNOSHZPbzAzSStRNi9tMUUKLS0tICtLZ0U3ZGxLOERKRVIvTVp5MnV3
            UUhKazRTOERXY0ZBRkNmVlIxUmpFQTAKunZbKcwFfak4Xfc4eeBwsvC5l6E7Ogfk
            gNYCyrmDOB3bVrbNXuSkFNXzNckTDxL0QlnnD6w0Hr+mhyLya3GDaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T09:05:58Z"
    mac: ENC[AES256_GCM,data:sZEKG5UGWC4dKl/jior1ZzhEvhkkdGvP98ANyXcwM1fG1+fTfwDDe458qa+mCelF9M66XLTvClgU5+B3zNjT2AJFZe+zmc0jFbA6ARAz72bSVbT/Cxmqf2WG7MvwYaz1aqXCnsLc2pZvOqv2xBA0CQmasyh1kZpe8fuAUCbFfL4=,iv:rm9oxdzr3HGkTtdH6fycQRgkOG/gWswJiNJzqJRFclU=,tag:mMB/PrBxkzKM7eUIPTQKHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
