gluetun:
    wireguardPrivateKey: ENC[AES256_GCM,data:AoE4JbatXrHxKkvJ2Jai1+koVfO/QqfMWeTiGD198m7rE2eM3zC2AMkszXE=,iv:XRN7WCE8RuXzgeF9EBd4iPENT6OLSMCHDShbhXysTyk=,tag:Us4UbA5phB9Pheh2T1oGiw==,type:str]
    wireguardAddresses: ENC[AES256_GCM,data:pNKg9wxkQX9LSSg=,iv:jSYfk4H5fjhlPX+E3Qk3rcMdpqw7cblRRvyOr8dX5oc=,tag:L6fjc2YrCNJRyXYAUYFnig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pq0dazk46s5mg8wdduccsx69sgu5namyls7q7pph0vx8nzrfsds0pnfvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMzNKSEtIZVM5TktoRzZy
            THBKaW9rN0IxTnBDSHdYYTJoaUhXYmJXTXpjCnRHai9JZ0ZFL0FMYnRxL1ZhdzF4
            TFNWdXBWSXZ0TkdhL0g0U1lqRlMvS1UKLS0tIFVMN2xLQ1pBRE1RZEdrK3oxck4r
            NjVFTzRtMnBwcGJscnByRm51bVRCZG8K6GoaAXlMrXCwM/LBS7p5y0CoZeyJT5Vh
            Db6iH+6+01YeP2ziep4VG9v8P1FbNBzRKq3Q7ViaiuzqLTd7narPMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T13:36:30Z"
    mac: ENC[AES256_GCM,data:jB/SbVkEQoV0F6shXLsPGVrxVIFOP9wids5vpVrEEjOZnoxDw+Gm2g4AC+EBLveSmlfdjwmpd/jiTO33/dHCV6IZ8QQzZwnpcvt5tTMTCH4gMYIjfRPTUmQscDhKNoD6TmNm1cSvaK3s107UzekZGEBpZTYZM5SeGT17hFAGaCo=,iv:9f7iP4wSaNHFvKQdDPJzZUtxva7SKFyK/Y16MlKJkA8=,tag:R2v6Bsaz150UiDQM5ZqgqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
