gluetun:
    wireguardPrivateKey: ENC[AES256_GCM,data:5S6dYqmJ57Ams1lPnjkzrehILsdtnUZokiqtkrZtFFFr6wM8xGRuTdukUdw=,iv:EBJKyQ+1NhWu97VGt9PqdCIgX+DI5qp2pzP/t3pVFRo=,tag:UWrCCnsS1VR8d5ERz96yGw==,type:str]
    wireguardAddresses: ENC[AES256_GCM,data:pNKg9wxkQX9LSSg=,iv:jSYfk4H5fjhlPX+E3Qk3rcMdpqw7cblRRvyOr8dX5oc=,tag:L6fjc2YrCNJRyXYAUYFnig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pq0dazk46s5mg8wdduccsx69sgu5namyls7q7pph0vx8nzrfsds0pnfvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMzNKSEtIZVM5TktoRzZy
            THBKaW9rN0IxTnBDSHdYYTJoaUhXYmJXTXpjCnRHai9JZ0ZFL0FMYnRxL1ZhdzF4
            TFNWdXBWSXZ0TkdhL0g0U1lqRlMvS1UKLS0tIFVMN2xLQ1pBRE1RZEdrK3oxck4r
            NjVFTzRtMnBwcGJscnByRm51bVRCZG8K6GoaAXlMrXCwM/LBS7p5y0CoZeyJT5Vh
            Db6iH+6+01YeP2ziep4VG9v8P1FbNBzRKq3Q7ViaiuzqLTd7narPMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T21:13:50Z"
    mac: ENC[AES256_GCM,data:mHfIVc1KVpOtW++qdJemunYu9DBxR69icPqOv+FmTsO2xjg08zd3wB0t3VVLqp8nZXU3sb9uNjiOm13PuvKFd9YXCz4MPoQuB639vZNx6Eo0k3Nv5EoazPG2j7N4qsWihVemHSeUPOOthSUa3pS9M3PXt87Hbkz5YGoAjarDEjE=,iv:V4l9kB/jf5ooXU45aG+vTYmCpbUXOr4JkGBXElbF0Bg=,tag:BMU4mt+9AN/Hs3gyNkJpTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
