apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glance.fullname" . }}-secrets
  labels:
    {{- include "glance.labels" . | nindent 4 }}
type: Opaque
stringData:
  TRUENAS_HOST: {{ .Values.secrets.truenasHost | quote }}
  TRUENAS_API_KEY: {{ .Values.secrets.truenasApiKey | quote }}
