image:
  repository: ghcr.io/flaresolverr/flaresolverr
  pullPolicy: IfNotPresent
  tag: "v3.5.0"

containerPort: 8191

env:
  TZ: "Europe/Paris"
  LOG_LEVEL: "info"

service:
  type: ClusterIP
  port: 8191

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "500m"
    memory: 512Mi
