apiVersion: v2
name: paperless
description: Helm chart for Paperless-ngx document management
version: 1.0.0
dependencies:
  - name: paperless-ngx
    version: 0.19.2
    repository: https://charts.gabe565.com
