paperless:
    secretKey: ENC[AES256_GCM,data:RySajlL69TjQSFbtqrkTqW0fObk2egOa6VbphGXkf2XA6VVZrqgqcIDf19oQUy3dQV466zlCzzm0EMeSxwVtGclf/zO1aKKxftRSC7Td7tzKYIdtiMH9MA==,iv:xKO02huPCnUUrntzvR7FAKRKvMcnG+rVbSTV2ttPHts=,tag:bEHIv+W1pkRmz5U5MAgqVA==,type:str]
    adminPassword: ENC[AES256_GCM,data:C7DpxQQFScWk425MkASMyv6Buyg=,iv:2tvbJjN9siqTyxbNnVJbonKViXTm0ZNp9hdhmteAyzE=,tag:eVyxpPTKNrtLepCZ0Etyew==,type:str]
    dbPassword: ENC[AES256_GCM,data:5CNfvl+ks6eC8SL5TWB/HGuVJVWsCSiUNNs+16yV2tf8//dZ3cUC6qSGyDU=,iv:Jl0QRAZhdAPfKcIHmkUhefzg+CCH/Ok+keEc3UTLl5g=,tag:rNo3ceAj1BZ5jDTycWe6tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pq0dazk46s5mg8wdduccsx69sgu5namyls7q7pph0vx8nzrfsds0pnfvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N3M2eGsxVXBsTHFOYlAx
            Rk1QeXlTMERzS1Z1RFo1MXJsZVQ3ZG90Rnk4ClJzelRrY3A4QTNLeC9oN2hxUG1j
            c1YxRFNpNUEvWWdzaHJQYzkzQXpUTkkKLS0tIE1vYmVsOEJnK0V4MS9pb2dNNTlZ
            cG5oVFYrZlk3c1V6U2RMd2lGVFF4czAKom2fT/IUIXY9XI+oFSfhZwdYP6y+IO6c
            gkYQ+xpaBZC5NgN3aiX7oYqnfAzQhE95oNHToq2XNFD5rVPKpnSdaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T20:12:47Z"
    mac: ENC[AES256_GCM,data:+hPB5QumcFP7F6OSFake+IOuZFWxJvrxmYsl+gDgu4YIxImdOtMn9tvL8Z5CpAV479E2n0ya0YpyceknYCIUQiXiDsLuFaFlpFlg1EDme/+pDZpRdTk7H8bqkYY5QqptgYs7pkxsuZEhQOYM8jP6FBL+9CUdwaM/xlEDZU5yljs=,iv:UxhDfyDraOiDW9TDyD3WOSDtmmxzlNPss9Wp8KWYYrU=,tag:vO1iGybK3Tcv4ThvY98scA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
