secretKey: ENC[AES256_GCM,data:FG9CNysSo4e3ws/4VnhnAnwtd7lfaHM0Pc+Kw0MXef3NsaCnO9jbDsr5FeCTWXuo74j1jnd1D5rjj7CnAVJ4lQ==,iv:xJo/awLXt5aZdcQTze08LfDQQjzhqKwiKHjUxheW8nY=,tag:gtVaJhPIYfPCz23eaptDZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pq0dazk46s5mg8wdduccsx69sgu5namyls7q7pph0vx8nzrfsds0pnfvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OVFRMlBmalozaysxZGtD
            OHFwU2lCNkJBVVBObms5MHNVaDF3TTNMdERzCjJ2Vkp2MklLbkR4Q0doR1lwcnpw
            Vm1OWU13ZW1Cc1hJbWZLUk9FK0dBNFEKLS0tIFNQM0tURWgzUmVUZU9Md3VzYmEw
            THNjWVBvbTZxT1dBcjN2RVlmMDV4UGcKpcCOighigz223CcyGimtjufv5I1P3647
            fd7Htnn/ziXeQz1Bd/4Fcz7iPkh8NozkfnaGT6Vfar5Kj1M1KiOwrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T09:51:47Z"
    mac: ENC[AES256_GCM,data:J/9MLKvdV4unuAfl8AdIJhKA5IyNK1WkKviRD6zRDXeTnA65R/K607tj3nO1IIsh+05fEM0WbhBe+MnMOAfdVqeOlXNt2QPM1/1hTZPcwAaGdVg0/4xlExkpFe/6A2PJ7otXYuxI2jbLOCTGrZvqPlFlw9smSSP52ZI2hJDMjjs=,iv:anXOQmJIMgUWGxwYzFqkoK35C0TNADDvjl2GXUh2Xx0=,tag:uwISvje9e6r4m/DaZU6zLA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
