image:
  repository: lscr.io/linuxserver/sonarr
  pullPolicy: IfNotPresent
  tag: "4.0.17.2952-ls310"

containerPort: 8989

securityContext:
  runAsUser: 3001
  runAsGroup: 3001
  fsGroup: 3001

env:
  TZ: "Europe/Paris"

auth:
  method: "External"

persistence:
  config:
    storageClass: longhorn
    size: 5Gi

service:
  type: ClusterIP
  port: 8989

ingress:
  enabled: true
  className: tailscale
  hosts:
    - host: sonarr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sonarr
      secretName: sonarr-tls

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi
