encryptionKey: ENC[AES256_GCM,data:WTlO6XrDleAM/p5CgxjdPKiwPKElSj3pTsIRmEXBwZA9t8dIdsW7yUtL6TkbKlTOQ0cSuft91jIJMJHd2b49tQ==,iv:27Ab6y8R5y9H/MAa5Atsjk7Qu6KmiAEtdmiE7+EVf5k=,tag:GRWFoItMsIbvLGPPHsqqCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pq0dazk46s5mg8wdduccsx69sgu5namyls7q7pph0vx8nzrfsds0pnfvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR09SQ3hiNm1WU0E5Ky84
            WEg4Zk0wSThaM1BuNFVHeGM5WERxZmZKdEdjCnUwbER2MTdQZzY1UFZxK3k2VVR5
            c1lYR21ONFRPSUszZ3NxZklVTzNsVGsKLS0tIGRzUHlYWk4wTitCcnM4YVRSNzdO
            czA3RVVFVFBRd2VkUmM5WXhSR1p2anMK1RbdwUOvMj4r2RupsdsQ2d4jf2ro7tRp
            MlYQ7r714PCrHkk2RumtvBHU9bJ+3igNnQTlDCbsRjYBMB+YOSGF8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T08:58:26Z"
    mac: ENC[AES256_GCM,data:vrN/JVLdAogECWEDY2EWdPoDTiIMIEtXkdan9Qw8/8DBfnwAbWmEocqGUidt+IrPm1dRR297SLBmgT9Ecgop1wUjhQvFaYLSocSpFJgIwEgJNnR5RAkuaug1YcHoBQg/HNna73YoNiuBoTDKlN+4foqAHDbolrOp+KSgpeFKoAs=,iv:kzX+GD9mfdT4jd7e1Hi45GmDBKUtZ1T3b8IAEYvU+8c=,tag:KzTSRgTelpQozqlPqc35+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
