apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bazarr.fullname" . }}-config
  labels:
    {{- include "bazarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
