apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-data-nfs
  resources:
    requests:
      storage: {{ .Values.nfs.capacity }}
