apiVersion: v1
kind: Secret
metadata:
  name: gluetun-vpn-credentials
  namespace: media
type: Opaque
stringData:
  wireguard-private-key: {{ .Values.gluetun.wireguardPrivateKey | quote }}
  wireguard-addresses: {{ .Values.gluetun.wireguardAddresses | quote }}
