radarr:
    apiKey: ENC[AES256_GCM,data:KoO2jysh4ZG04i8w9KVGBNB9N/DBeMTQuPr0kn3qcgk=,iv:57fkv3Ci1wMf8ECPl/WOaCctK1aC10GNzUsM3X9PrMY=,tag:809chA7xSvNbc1CjPmeATA==,type:str]
sonarr:
    apiKey: ENC[AES256_GCM,data:lI+GQoRy8u6RCvSwjHcAQgucCESi8M+wxRnVBK3fjUE=,iv:/yxCidjbNrats16a40qLzT/kqLjM85Jra+6kt3CkyA8=,tag:2lBR0JpA9MRWS7lLCOy02g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pq0dazk46s5mg8wdduccsx69sgu5namyls7q7pph0vx8nzrfsds0pnfvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TURxSWg1TlR5K1Noc3l2
            SVpZSXpKL2J2SmVYclRMUWwvMU43TmJDTUIwCkowdTdVeXlPVVMxU1JSclhzWTJL
            QmkxeldmbThmcDZyOE1WeTJYZGk2TEEKLS0tIGpGcDQ3OThVbHFCUmpTcXRwNG8y
            VWl3MzVyMVM0eVJrN1oxOThyY0ZDVHcKpGBYye2FKuCyCSAYfCTrMp1CP8l8qWN/
            viiKyzE+c+eYUDlFRmlQ2Tx48AUUMhIY+pdtyuU6C8m4cwUe9a6ktw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T16:09:20Z"
    mac: ENC[AES256_GCM,data:22QHBz4WYxmreEOQUe9yhaCAIoiUkX1vchFwW3IVWABbpxbbUFkKBItbsIdS5ya02bk3/CltMpI3wrujGnpz0rRA+cB+0Q9u1gFISHj/eIPsTgV54stJtWplO8rgQsPzx9TnLc32B92/FD1+pYclNCfNyTXUIeZ8td/XIXfhq6Q=,iv:0gXt0N9bLxj9yMT4yEENg/77skE9YctISpurQ1WakEI=,tag:tRK9zxxWliJFjlvzuwVU8Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
