seerr-chart:
  extraEnv:
    - name: TZ
      value: "Europe/Paris"

  config:
    persistence:
      storageClass: longhorn
      size: 2Gi

  ingress:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/funnel: "true"
    hosts:
      - host: seerr
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - seerr
        secretName: seerr-tls

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi
