apiVersion: v1
kind: Service
metadata:
  name: {{ include "snapotter.fullname" . }}-redis
  labels:
    {{- include "snapotter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "snapotter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
