apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unpackerr.fullname" . }}
  labels:
    {{- include "unpackerr.labels" . | nindent 4 }}
type: Opaque
stringData:
  radarr-api-key: {{ .Values.radarr.apiKey | quote }}
  sonarr-api-key: {{ .Values.sonarr.apiKey | quote }}
