apiVersion: v1
kind: Secret
metadata:
  name: paperless-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  secret-key: {{ .Values.paperless.secretKey | quote }}
  admin-password: {{ .Values.paperless.adminPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-db-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: paperless
  password: {{ .Values.paperless.dbPassword | quote }}
