image:
  repository: lscr.io/linuxserver/bazarr
  pullPolicy: IfNotPresent
  tag: "1.6.0"

containerPort: 6767

securityContext:
  runAsUser: 3001
  runAsGroup: 3001
  fsGroup: 3001

env:
  TZ: "Europe/Paris"

persistence:
  config:
    storageClass: longhorn
    size: 1Gi

service:
  type: ClusterIP
  port: 6767

ingress:
  enabled: true
  className: tailscale
  hosts:
    - host: bazarr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - bazarr
      secretName: bazarr-tls

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi
