- type: custom-api
  title: Gluetun status
  cache: 1m
  url: http://gluetun.media.svc.woohp.local:8320/v1/vpn/status
  options:
    show-forwarded-port: true
  template: |
    {{ if eq .Response.StatusCode 200 }}
      {{ $status := (.JSON.String "status") }}
      {{ if eq $status "running" }}
        {{ $ipResp := newRequest "http://gluetun.media.svc.woohp.local:8320/v1/publicip/ip" | getResponse }}
        {{ $ip := "" }}
        {{ $city := "" }}
        {{ $country := "" }}
        {{ if eq $ipResp.Response.StatusCode 200 }}
          {{ $ip = ($ipResp.JSON.String "public_ip") }}
          {{ $city = ($ipResp.JSON.String "city") }}
          {{ $country = ($ipResp.JSON.String "country") }}
        {{ end }}
        <div>
          <div>
            <div>
              <div class="color-highlight size-h3">
                Your VPN is connected!
                <span class="color-positive">●</span>
              </div>
            </div>
            {{ if ne $ip "" }}
              <div class="size-h5">{{ $ip }} - {{ $city }}, {{ $country }}</div>
            {{ end }}
          </div>
        </div>
      {{ else }}
        <div>
          <div>
            <div>
              <div class="color-highlight size-h3">
                Your VPN is not connected!
                <span class="color-negative">●</span>
              </div>
            </div>
          </div>
        </div>
      {{ end }}
    {{ else }}
      <div style="text-align: center; color: var(--color-negative);">
        Error: {{ .Response.StatusCode }} - {{ .Response.Status }}
      </div>
    {{ end }}

    {{ $showForwardedPort := .Options.BoolOr "show-forwarded-port" false }}

    {{ if $showForwardedPort }}
      {{
        $resp := newRequest "http://gluetun.media.svc.woohp.local:8320/v1/portforward"
          | getResponse
      }}
      {{ if eq $resp.Response.StatusCode 200 }}
        {{ $port := ($resp.JSON.String "port") }}
        <div>
            <div>
              <div class="size-h5">Port: {{ $port }}</div>
            </div>
          </div>
      {{ else }}
        <p>Failed to fetch port</p>
      {{ end }}
    {{ end }}
