apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "radarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap-init.yaml") . | sha256sum }}
      labels:
        {{- include "radarr.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: radarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
            - name: RADARR_CONFIG_DIRECTORY
              value: "/config"
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media-data
              mountPath: /data
            - name: radarr-init
              mountPath: /custom-cont-init.d
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "radarr.fullname" . }}-config
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data
        - name: radarr-init
          configMap:
            name: {{ include "radarr.fullname" . }}-init
            defaultMode: 0755
